# Docker Compose pour OSRM local - Installation ultra-rapide
# Usage: docker-compose -f docker-compose.osrm.yml up -d

version: '3.8'

services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm-local
    ports:
      - "5000:5000"
    volumes:
      - osrm-data:/data
    command: >
      bash -c "
      if [ ! -f /data/france-latest.osrm ]; then
        echo 'Téléchargement des données cartographiques de la France...'
        wget -O /data/france-latest.osm.pbf http://download.geofabrik.de/europe/france-latest.osm.pbf
        echo 'Extraction des données routières...'
        osrm-extract -p /opt/car.lua /data/france-latest.osm.pbf
        echo 'Partition des données...'
        osrm-partition /data/france-latest.osrm
        echo 'Personnalisation des données...'
        osrm-customize /data/france-latest.osrm
        echo 'OSRM initialisé avec succès !'
      fi
      echo 'Démarrage du serveur OSRM...'
      osrm-routed --algorithm mld /data/france-latest.osrm --port 5000 --ip 0.0.0.0
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    environment:
      - OSRM_THREADS=4
    mem_limit: 4g
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  osrm-data:
    driver: local